### ISSUE TITLE
Does not work with sqlite

### ISSUE THREAD

**Issue by TheNomad11** [toteph42/identy_switch#1]
When I installed the plugin I got an error message that I unfortunately did not write down. It might be this own from my clipboard_

`Creating database schema... ERROR: [1] near "KEY": syntax error (SQL Query: CREATE TABLE IF NOT EXISTS "identy_switch"`

This was a Roundcube installation with sqlite

When I installed the plugin on another installation with mariadb, it worked perfectly.

**Comment by toteph42** [comment]
Should be fixed now in 1.0.6. Please try again.
