### ISSUE TITLE
Wildcard for domains

### ISSUE THREAD

**Issue by HostOncilla** [toteph42/identy_switch#17]
Would it be possible to add something like this

`'*' => [
		'imap' => 'ssl://mail.*.tld:993',
		'user' => 'email',
		'smtp' => 'tls://mail.*.tld:487',
	],`

The * would be a wildcard to grab the domain for the identity email address. I use it on a server with lots of domains so it would be very handy to have this option.

Also is there a way to add a default "Folder hierarchy delimiter" for the domains?

**Comment by toteph42** [comment]
Implemented in 1.0.26
