### ISSUE TITLE
Invisible Emails

### ISSUE THREAD

**Issue by pukpuker** [toteph42/identy_switch#19]
![image](https://github.com/user-attachments/assets/f1145314-6477-47ef-b3ed-94c443495836)
Just invisible mails after enabling this plugin

**Comment by toteph42** [comment]
First, you need to specify identities. Second: Which version are you using?

**Comment by pukpuker** [comment]
Roundcube Webmail 1.6.7
I have already created several identifiers

**Comment by toteph42** [comment]
Which theme do you use?

**Comment by pukpuker** [comment]
default black.

**Comment by toteph42** [comment]
Sorry I can't help you. If cannot describe how I can reproduce the bug, I cannot help you. 

I assume you forgot to put in an label description. Empty label = nothing shown.
