### ISSUE TITLE
Main account SMTP error

### ISSUE THREAD

**Issue by HostOncilla** [toteph42/identy_switch#20]
SMTP comes up with a sending error when trying to send from main account.

**Comment by toteph42** [comment]
Add 
`// Log sent messages to <log_dir>/sendmail.log or to syslog`
`$config['smtp_log'] = true;`

`// Log SMTP conversation to <log_dir>/smtp or to syslog`
`$config['smtp_debug'] = true;`

to your `config.inc.php`. Then you should see what's going wrong. Add results to this post and I'll check if I can help.

**Comment by HostOncilla** [comment]
If the plugin is enabled I get the following log in smtp.log

`Connecting to tls://%h:587...`

**Comment by toteph42** [comment]
Do you use `%h` in `ident_switch/config.inc.php`? Plugin does not support any substitution characters. It only swaps data...

**Comment by HostOncilla** [comment]
No I don't, it's getting the %h from config/config.inc.php

**Comment by toteph42** [comment]
Fixed in 1.0.28
