### ISSUE TITLE
Extended Skin

### ISSUE THREAD

**Issue by HostOncilla** [toteph42/identy_switch#21]
I have an extended skin (child-skin of elastic) of elastic which I use with meta.json, the problem is that every time there's an update I have to rename:

```
case 'elastic':
        isOk = identy_switch_addCbElastic($sw);
```

To:

```
case 'hivemail':
        isOk = identy_switch_addCbElastic($sw);
```

Is there anyway around this?

**Comment by toteph42** [comment]
Fix in 1.0.29
