### ISSUE TITLE
Feature request: Add unread e-mail counter

### ISSUE THREAD

**Issue by CodeShakingSheep** [toteph42/identy_switch#22]
Hi @toteph42 ,
in my opinion it would be great to have an unread mail counter in the mail address dropdown, so that the user knows which mail addresses are worth checking.

![image](https://github.com/user-attachments/assets/57ea4c99-3a2c-4777-b0ee-803d55d2b546)

Let me know if you think that this can be implemented.

**Comment by toteph42** [comment]
This is already implemented. Depending on your mail check configuration it is automatically done in the back ground.

**Comment by CodeShakingSheep** [comment]
Can you elaborate on how it is supposed to work? I have these settings for an identity. 
![image](https://github.com/user-attachments/assets/5e492d61-8e9f-4acf-a57f-207305cf79d4)

I receive desktop notifications but there is no counter (as I drafted it in my screenshot). What am I missing?

**Comment by toteph42** [comment]
Notification for desktop is

`$labels['notify.msg'] = '%d for %s';`

`%d` is number of new mails. `%s` is identity label

I don't know what else could be displayed.

**Comment by CodeShakingSheep** [comment]
I'm not talking about the desktop notification. That works fine. 

I'm talking about an additional permanent way to display the number of unread mails. As the nature of the desktop notification is temporary (displayed between 10 and 60 seconds) you can easily miss it if you are afk for some time. So having a permanent way to display the number of unread mails would really be beneficial in my opinion. This feature has also been requested in the original repository, see https://bitbucket.org/BoresExpress/ident_switch/issues/21/new-mail-count-next-to-identity-label .

So, I appreciate if you can let me know whether you think you can implement this.

**Comment by toteph42** [comment]
This is already implemented
![grafik](https://github.com/user-attachments/assets/0632f065-dfd3-453e-8a8e-305dfd64a78b)
I don't understand your request. Sorry.

**Comment by CodeShakingSheep** [comment]
Ah I see. For some reason it's not working for me. That's why I asked you how this is supposed to work and if I need to enable it in the settings or if it's enabled by default.

This is how it looks for me. I never see the counter although some of my mail addresses definitely do have unread mails.
![image](https://github.com/user-attachments/assets/723b8291-2acb-4c49-9a7e-c0a87d88c1a2)

Do you have an idea what could be the reason? BTW, I'm on identy_switch version 1.0.29. Will update to the latest version tomorrow.

**Comment by toteph42** [comment]
Check out new version  - it work's faster displaying unread count than previous version

**Comment by CodeShakingSheep** [comment]
I just updated to the new version. Still, I don't see any counters beneath the labels although several of my accounts have unread mails in the inbox. As I also wrote you, I had never seen them in the past which is why I initially opened this issue for a feature request. Is there any way we can debug this together?

**Comment by toteph42** [comment]
Yes, enable debugging in config file.

**Comment by CodeShakingSheep** [comment]
> Yes, enable debugging in config file.

Just `$config['debug_level']=1` in `conf/config.inc.php` or anything else?

**Comment by toteph42** [comment]
Of course you need to post `logs/identy_switch.log` after approx. 5 minutes. Then disable debugging again.
