### ISSUE TITLE
PHP error in identy_switch_newmails.php when document root is set to public_html

### ISSUE THREAD

**Issue by buttercookie42** [toteph42/identy_switch#27]
If I set the document root to `<roundcube install directory>/public_html` (as e.g. recommended in the Roundcube installation instructions), identy_switch starts throwing a PHP error:

> mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Failed opening required '/var/www/vhosts/REDACTED/www/RC_install_dir/public_html/program/include/iniset.php' (include_path='.:/usr/local/php83/share/php83') in /var/www/vhosts/REDACTED/www/RC_install_dir/plugins/identy_switch/identy_switch_newmails.php:14

The problem is https://github.com/toteph42/identy_switch/blob/8b3ff63a947bda3c5c8b1ee83941c3abd7cd3872/identy_switch_newmails.php#L13
which obviously doesn't work when the document root is set to the public_html subfolder.

I'm not sure if there's a proper, less hacky solution there, otherwise the best workaround I can come up with would be replacing that line with `define('INSTALL_PATH', realpath(__DIR__ . '/../..') . '/');`, i.e. assuming that the Roundcube install dir must be two levels up from the plugin's base dir.

**Comment by toteph42** [comment]
Fixed in 1.0.35
