### ISSUE TITLE
Dropdown menu position doesn't take account of additional buttons in Classic skin

### ISSUE THREAD

**Issue by buttercookie42** [toteph42/identy_switch#28]
I have some plugins enabled that add additional buttons (e.g. markasjunk and thunderbird_labels), and the result is that with the Classic skin, the menu now sits over some of those buttons:

![grafik](https://github.com/user-attachments/assets/16b1208e-bb7e-4f3e-8129-704ab38bf70d)

(To be honest, for the Classic skin the old "ident_switch" position of the dropdown menu next to the "E-Mail" button on the upper right wasn't too bad, actually.)

**Comment by toteph42** [comment]
Fixed in 1.0.35
