### ISSUE TITLE
Dropdown menu popup appears underneath message list header with Classic skin in desktop mode

### ISSUE THREAD

**Issue by buttercookie42** [toteph42/identy_switch#29]
If I'm using the Classic skin with the message view in "Desktop" mode, the selection dropdown popup appears underneath the message list heading:

![grafik](https://github.com/user-attachments/assets/9953db89-605e-4257-83d2-db54bbd55220)

**Comment by toteph42** [comment]
Cannot reproduce
![Screenshot 2024-10-10 103013](https://github.com/user-attachments/assets/8e9ddebd-ba72-4bf0-b63e-5e80fb69063b)

**Comment by buttercookie42** [comment]
I meant the dropdown panel in its *opened* state. Plus I *did* say with the mailbox view set to "Desktop (wide list and mail preview below)". "Widescreen (3-column view)" works indeed fine, because in that case the dropdown panel only overlaps the message previews and that doesn't cause any z-level conflicts (unless you adjust the default column widths – with a wider message list the problem would of course appear there, too).

Since with the default theme the confliction `#messagelist-fixedcopy` element is already at z-level 2, the only workaround I've found is overriding the z-level of the whole Classic theme's `#toolbar` to 3 or higher.

**Comment by toteph42** [comment]
Fixed in 1.0.36
