### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identy_switch#31]
nginx 1.26.2, php-fpm 8.1.30, roundcube 1.6.9 

plugin downloaded from master, with standard identify config (imap/143, smtp/25)

2024/10/25 23:41:56 [error] 1758#1758: *12974 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php:468
Stack trace:
#0 /var/www/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(520): identy_switch->catch_newmails()
#1 /var/www/roundcubemail/program/actions/mail/check_recent.php(99): rcube_plugin_api->exec_hook()
#2 /var/www/roundcubemail/program/include/rcmail.php(282): rcmail_action_mail_check_recent->run()
#3 /var/www/roundcubemail/index.php(278): rcmail->action_handler()
#4 {main}
  thrown in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 468" while reading response header from upstream

**Comment by toteph42** [comment]
Should be fixed with 1.0.38
