### ISSUE TITLE
php warning (1.0.38)

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identy_switch#32]
nginx 1.26.2, php-fpm 8.1.30, roundcube 1.6.9

2024/10/26 22:10:25 [error] 1758#1758: *56717 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "folders" in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 363" while reading response header from upstream, client: xx.xx.xx.xx, server: xxx.xxx, request: "POST /?_task=mail&_action=plugin.identy_switch_do HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=mail&_mbox=INBOX"

**Comment by toteph42** [comment]
Fixed with 1.0.39
