### ISSUE TITLE
some php warnings in 1.0.39

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identy_switch#33]
nginx 1.26.2, php-fpm 8.1.30, roundcube 1.6.9 (migrated from ident_switch):

> 2024/10/27 20:39:06 [error] 1838777#1838777: *63 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "flags" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 123PHP message: PHP Warning:  Undefined array key "flags" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 124PHP message: PHP Warning:  Undefined array key "imap_pwd" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 126PHP message: PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/roundcubemail/program/lib/Roundcube/rcube.php on line 945" while reading response header from upstream, client: 127.0.0.1, server: xxx.xxx, request: "GET /plugins/identy_switch/identy_switch_newmails.php?iid=2651&cache=%2Fvar%2Fwww%2Froundcubemail%2Ftemp%2Fidenty_switch_cache.u53kj62jh0s4c3v4djacctf154 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx"

> 2024/10/27 20:39:07 [error] 1838777#1838777: *59 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "checked_last" in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 521PHP message: PHP Warning:  Undefined array key "unseen" in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 658PHP message: PHP Warning:  Undefined array key "notify" in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 661" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx, request: "POST /?_task=mail&_action=refresh HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=mail&_mbox=INBOX"

> 2024/10/27 20:39:30 [error] 1838859#1838859: *55 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "folders" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 143PHP message: PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 143" while reading response header from upstream, client: 127.0.0.1, server: xxx.xxx, request: "GET /plugins/identy_switch/identy_switch_newmails.php?iid=2587&cache=%2Fvar%2Fwww%2Froundcubemail%2Ftemp%2Fidenty_switch_cache.p1k5usf5700cbii7v3sjvv48b6 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx"

**Comment by toteph42** [comment]
I think this is related to Issue #34. 
Warning #1 + #2:
If this variable isn't set, then communication between task running in foreground and in background crashed. No chance to fix.
Warning #3:
Fixed in 1.0.40 - but should also not appear if you configured special folders correctly in Roundcube.

**Comment by pikachurus** [comment]
sorry, but with 1.0.40 same warning, on the same line:

> 2024/10/28 20:45:32 [error] 809951#809951: *3267 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "folders" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 143PHP message: PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 143" while reading response header from upstream, client: 127.0.0.1, server: xxx.xxx, request: "GET /plugins/identy_switch/identy_switch_newmails.php?iid=2262&cache=%2Fvar%2Fwww%2Froundcubemail%2Ftemp%2Fidenty_switch_cache.r3hhes16fbe2g3ht5vemov5ub6 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx"

and special folders on mail accounts are pretty standard:
![image](https://github.com/user-attachments/assets/abc576e5-5d36-4372-b394-966fde59748f)

**Comment by toteph42** [comment]
Yes, Fixed in 1.0.41
