### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identy_switch#35]
identy_switch 1.0.41:

> [error] 809951#809951: *526505 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key 2 in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 607PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php:607
> #0 /var/www/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(520): identy_switch->check_newmails()
>   thrown in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 607" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: mail.ronc.ru, request: "POST /?_task=mail&_action=refresh HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=mail&_mbox=INBOX"
>

**Comment by toteph42** [comment]
A potential workaround for this php8.1-fpm.sock: problem is included in 1.0.42.
