### ISSUE TITLE
php error + 2 warnings

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identy_switch#37]
identy_switch 1.0.43:

> 2024/11/01 10:11:16 [error] 1504#1504: *94908 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php:611
> Stack trace:
> #0 /var/www/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(520): identy_switch->check_newmails()
> #1 /var/www/roundcubemail/program/include/rcmail.php(228): rcube_plugin_api->exec_hook()
> #2 /var/www/roundcubemail/index.php(278): rcmail->action_handler()
> #3 {main}
>   thrown in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 611" while reading response header from upstream, client: 192.168.66.37, server: xxx.xxx, request: "GET /?_task=mail&_action=getunread&_page=1&_remote=1&_unlock=0&_=1730445075854 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=mail&_mbox=INBOX"

> 2024/11/01 10:10:07 [error] 1504#1504: *62818 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "checked_last" in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 521" while reading response header from upstream, client: 192.168.65.29, server: xxx.xxx, request: "POST /?_task=mail&_action=refresh HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=mail&_mbox=INBOX"

> 2024/11/01 10:20:28 [error] 1504#1504: *62818 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "flags" in /var/www/roundcubemail/plugins/identy_switch/identy_switch.php on line 295" while reading response header from upstream, client: 192.168.65.29, server: xxx.xxx, request: "GET /?_task=mail&_mbox=INBOX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=settings&_action=identities"

**Comment by pikachurus** [comment]
there's no problem with cache folder:

> -rw-r--r--  1 www-data www-data     1268 nov  1 09:26 identy_switch_cache.vv62n5pkm9qfnocjva2dub7ee1
> -rw-r--r--  1 www-data www-data     1211 oct 28 08:26 identy_switch_cache.vvo7pch9504kes3jo5qt15gmqj
> -rw-r--r--  1 www-data www-data      242 nov 12 13:16 identy_switch_ret.fmef2vevcn8pto95gj4tggs6gg
> -rw-r--r--  1 www-data www-data      242 nov 12 13:15 identy_switch_ret.gbem6uf54pm80ebvufabn3lp35
> -rw-r--r--  1 www-data www-data      242 nov  1 10:20 identy_switch_ret.gt621nahriel0p1kotnt8jq5qs


in identy_switch.logs mostly:

> [12-Nov-2024 13:21:19 +0300]: <un1ncf14> Cache file "/var/www/roundcubemail/temp/identy_switch_cache.un1ncf14h3snnk53i64ta2kc03" created
> [12-Nov-2024 13:21:22 +0300]: <4cjev7et> Cache file "/var/www/roundcubemail/temp/identy_switch_cache.4cjev7etb0vafendnh8u6h0snn" created


but something happens and:

> [12-Nov-2024 13:21:06 +0300]: <8f0a8n2p> NewMail error: "HTTP/1.1 503 Service Temporarily Unavailable" for "xxx.xxx" Request: "/plugins/identy_switch/identy_switch_newmails.php?iid=-1&cache=%2Fvar%2Fwww%2Froundcubemail%2Ftemp%2Fidenty_switch_cache.8f0a8n2pfmcc96fpcc8jku9kdc"


in nginx.log:

> 2024/11/12 13:21:40 [error] 1504#1504: *5906490 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.65.48, server: xxx.xxx, request: "POST /?_task=mail&_action=refresh HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=mail&_mbox=INBOX"

when i change identy_switch to ident_switch in config.php - everything is back to normal.
i'm tuned some php and nginx settings (workers, memory, etc) but nothing helps.

when identy_switch is enabled, some mailboxes may freezes with "refreshing" on top screen.

so i back to ident_switch for now, thanks for your help!

**Comment by toteph42** [comment]
Thank you for the additional information. 

You can make `identy_switch` work like `ident_switch` by disabling new mail check in `config.inc.php`. 

Otherwise you can increase `interval`  (new mail checking) for each identity to delay checking. 

Finally I implemented one additional configuration parameter `delay` which you can use to delay the requests for new mail checks in version 1.0.44

**Comment by pikachurus** [comment]
it seems problem with infinite "Refreshing" (with a further php error) appears when 'check' is enabled.

> You can make identy_switch work like ident_switch by disabling new mail check in config.inc.php.

that's what I did, and now it works fine for me.
