### ISSUE TITLE
Username of the current mailbox is not displayed if identity_switch is not used in this profile.

### ISSUE THREAD

**Issue by svjat-orb** [toteph42/identy_switch#38]
Hello. Identity_switch version 1.0.43. Roundcube version 1.6.8. There is an issue with displaying the current user's name in the Roundcube interface when the identity_switch plugin is enabled. If the user has not created a new identity, their name does not appear in the headers.

![Screenshot_20241102_113838](https://github.com/user-attachments/assets/dc4c2173-5f77-495f-ab92-eb004a656819)

**Comment by toteph42** [comment]
Thank you for your input. I tested with RC 1.59 and everything should normal:
![grafik](https://github.com/user-attachments/assets/fe554cad-188a-4ca7-ac85-3a588956f5b7)
If you go to `Setting->Identities` there should only one entry. `identy_switch` table is empty and table `identity` has only one automatically created record for main identity.

**Comment by lumian** [comment]
Hello! We are seeing the same problem on RC version 1.6.9. An empty space is displayed instead of the mailbox.
If you add at least one additional profile, then everything becomes fine and the selection of the mailbox is displayed in an empty place.
![2024-11-05_07-42-20](https://github.com/user-attachments/assets/66c39195-a06c-4275-b17f-98aafc3154fb)

**Comment by toteph42** [comment]
Hi,
the problem is: As long as I cannot reproduce the error, I'll can't fix it :-)

**Comment by toteph42** [comment]
Hi,
tried 3x - one time e-Mail does not appear. Analyzed. Table `identity` was empty. Not my problem. Roundcube forgot to store record into `identity` table. That's beyond my scope. Try to logout/login and E-Mail will appear as expected.

**Comment by mydrec777rus** [comment]
Hello! We are seeing the same problem on RC version 1.6.11. An empty space is displayed instead of the mailbox.
If you add at least one additional profile, then everything becomes fine and the selection of the mailbox is displayed in an empty place.

**Comment by toteph42** [comment]
Hi,
was fortunately able to locate problem. Fixed in 1.1.21
