### ISSUE TITLE
Undefined constant PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT during install

### ISSUE THREAD

**Issue by dricetea** [toteph42/identy_switch#39]
I’m having problems installing https://github.com/toteph42/identy_switch 1.0.44

Composer log:

./composer.json has been updated
Running composer update toteph42/identy_switch
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing toteph42/identy_switch (1.0.44): Extracting archive
    Unzipping using 7z 16.02 may result in incorrect file permissions. Install 7z 21.01+ or unzip to ensure you get correct permissions.
Do you want to activate the plugin identy_switch? [Y|n] Y
Creating package config file
Running database initialization script for identy_switch
    Install of toteph42/identy_switch failed

In mysql.php line 125:

  [Error]
  Undefined constant PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT

PHP module pdo_mysql is activated

I manualy created the table https://github.com/toteph42/identy_switch/blob/master/SQL/mysql.initial.sql
and updated the attribute according https://github.com/toteph42/identy_switch/blob/master/SQL/mysql/20240827.sql

but it did not helped…

In Roundcube 1.6.9 the plugin is listed in the about - but not working yet…

Any idea how I could get it working?

BR,
Dr Icetea

**Comment by toteph42** [comment]
Hi,
neither is there a `mysql.php` included in the plugin, nor does I use `MYSQL_ATTR_SSL_VERIFY_SERVER_CERT`. Indeed, this file is part of RoundCube itself - see `program/lib/Roundcube/db/mysql.php`. 

A short query brought up: The constant exists as of PHP 7.0.18 and PHP 7.1.4. 
It seems you use a very old PHP version ;-). I would suggest to update your PHP installation.

**Comment by dricetea** [comment]
Hi,
thanks for the quick hint 8-) 
I had to run composer in version 8.2 - by default it took version 7.4... installation completed now without an issue
