### ISSUE TITLE
Undefined array key "delay"

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identy_switch#40]
1.0.44:

> 2024/11/18 14:29:17 [error] 1504#1504: *8719322 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "delay" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_newmails.php on line 94" while reading response header from upstream, client: 127.0.0.1, server: xxx.xxx, request: "GET /plugins/identy_switch/identy_switch_newmails.php?iid=0&cache=%2Fvar%2Fwww%2Froundcubemail%2Ftemp%2Fidenty_switch_cache.dpu40hsi19pjvvnbf0o4kagnb8 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx"

in config.inc.php:

> 'delay' => 10000000,

**Comment by toteph42** [comment]
Fixed in 1.0.45
